import 'dotenv/config'

const env = {
  PORT: process.env.PORT,
  MONGODB_NAME: process.env.MONGODB_NAME,
  MONGODB_USERNAME: process.env.MONGODB_USERNAME,
  MONGODB_PASSWORD: process.env.MONGODB_PASSWORD,
  MONGODB_USERS_COLLECTION: process.env.MONGODB_USERS_COLLECTION,
  SALT_PASSWORD: process.env.SALT_PASSWORD,
  JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
  ACCESS_TOKEN_EXPIRES_IN: process.env.ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_EXPIRES_IN: process.env.REFRESH_TOKEN_EXPIRES_IN
}

export default env
